### ISSUE TITLE
SitemapGenerator properties inheritance

### ISSUE THREAD

**Issue by dloubere** [tommy-muehle/silex-sitemap-service-provider#2]
Given an internationalized website, one has to declare specific nodes into sitemaps as follow:

```
<xhtml:link 
    rel="alternate"
    hreflang="de"
    href="http://www.example.com/deutsch/"
    />
```

Could you consider making the provider "extendable" to enable the overriding of the `SitemapGenerator` class?

**Comment by tommy-muehle** [comment]
Thank you @davidloubere for the feedback. I changed the variable visibility in release 1.1.1 to solve your issue. By doing that i saw many hardcoded values from the first implementation 2014. 
So i decided to also fix that. The result is a new version 2.0 because of some api changes. Feel free to try any of this versions.

**Comment by dloubere** [comment]
Thank you for the changes!
